language: scala
sudo: false
cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
matrix:
  include:
    # Spark 2.0.0
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.0.1" LUCENE_ANALYZER="en"
    - jdk: oraclejdk8
      scala: 2.11.8
      env: TEST_SPARK_VERSION="2.0.1" LUCENE_ANALYZER="whitespace"
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean update -Dlucenerdd.analyzer.name=${LUCENE_ANALYZER} -test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION assembly
  - travis_wait 30 sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)
